# base image
FROM node:14.16.0

# set working directory
WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]
RUN npm install 
RUN npm install react-scripts@4.0.3 -g

COPY . .

# 앱 실행
CMD ["npm", "start"]